#!/usr/bin/env python
# -*- coding: utf-8 -*-

import cups

class CupsPPDs:
    def __init__(self):
        self.cups_conn = cups.Connection()
        self.ppds = self.cups_conn.getPPDs2()

    def dump_makes(self):
        makes = []
        ppds = self.ppds
        for drv, ppd in ppds.iteritems():
            if not  ppd['ppd-make'][0] in makes:
                makes.append(ppd['ppd-make'][0])
        makes.sort()
        for val in makes:
            print val

    def dump_models(self, make):
        models = []
        ppds = self.ppds
        for drv, ppd in ppds.iteritems():
            if ppd['ppd-make'][0] == make:
                models.append(ppd['ppd-make-and-model'][0])
        models.sort()
        for val in models:
            print val

if __name__ == '__main__':
    cups_ppds = CupsPPDs()
    cups_ppds.dump_makes()
    cups_ppds.dump_models('HP')
