#!/usr/bin/env python
# -*- coding: utf-8 -*-

import cups

class CupsPPDs:
    def __init__(self):
        self.cups_conn = cups.Connection()
        self.ppds = self.cups_conn.getPPDs2()

    def dump_makes(self):
        makes = []
        ppds = self.ppds
        for drv, ppd in ppds.iteritems():
            if not  ppd['ppd-make'][0] in makes:
                makes.append(ppd['ppd-make'][0])
        makes.sort()
        for val in makes:
            print val

    def dump_models(self, make):
        models = []
        ppds = self.ppds
        for drv, ppd in ppds.iteritems():
            if ppd['ppd-make'][0] == make:
                models.append(ppd['ppd-make-and-model'][0])
        models.sort()
        for val in models:
            print val

    def show_network_available(self):
        dev = self.cups_conn.getDevices()
        for uri, info in dev.iteritems():
            if uri.find("://") > 0:
                print "uri: {0} , info: {1}".format(uri, info['device-info'])

if __name__ == '__main__':
    cups_ppds = CupsPPDs()
    cups_ppds.dump_makes()
    cups_ppds.dump_models('HP')
    cups_ppds.show_network_available()
